import { defineConfig } from 'bunup'

export default defineConfig({
	entry: [
		'src/index.ts',
		'src/adapter/index.ts',
		'src/adapter/createValidator.ts',
		'src/adapter/createTransformer.ts',
		'src/adapter/adapters/zod-v4.validator.ts',
		'src/adapter/adapters/zod-v4.transformer.ts',
		'src/adapter/adapters/zod-v3.validator.ts',
		'src/adapter/adapters/zod-v3.transformer.ts',
		'src/adapter/adapters/valibot.validator.ts',
		'src/adapter/adapters/valibot.transformer.ts',
		'src/adapter/adapters/arktype.validator.ts',
		'src/adapter/adapters/arktype.transformer.ts',
		'src/adapter/adapters/yup.validator.ts',
		'src/adapter/adapters/yup.transformer.ts',
		'src/adapter/adapters/joi.validator.ts',
		'src/adapter/adapters/joi.transformer.ts',
		'src/adapter/adapters/io-ts.validator.ts',
		'src/adapter/adapters/io-ts.transformer.ts',
		'src/adapter/adapters/superstruct.validator.ts',
		'src/adapter/adapters/superstruct.transformer.ts',
		'src/adapter/adapters/typebox.validator.ts',
		'src/adapter/adapters/typebox.transformer.ts',
		'src/adapter/adapters/effect.validator.ts',
		'src/adapter/adapters/effect.transformer.ts',
		'src/adapter/adapters/runtypes.validator.ts',
		'src/adapter/adapters/runtypes.transformer.ts',
	],
	format: ['esm'],
	dts: true,
	clean: true,
	sourcemap: false,
	splitting: true,
	minify: false,
	external: [
		// Schema libraries - don't bundle these
		'zod',
		'zod/v4',
		'valibot',
		'arktype',
		'yup',
		'joi',
		'io-ts',
		'fp-ts',
		'superstruct',
		'@sinclair/typebox',
		'@sinclair/typebox/value',
		'@effect/schema',
		'@effect/schema/Schema',
		'effect',
		'runtypes',
		// JSON Schema converters
		'zod-to-json-schema',
		'@valibot/to-json-schema',
	],
})
